version: '2'

volumes:
  postgres_data_dev: {}

services:
  postgres:
    image: postgres:11.2
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./dumps:/tmp/dumps

  redis:
    image: redis:4

  django:
    working_dir: /app/
    build:
      context: .
      dockerfile: ./Dockerfile
    image: django-react/boilerplate:dev
    command: python -Wall manage.py runserver_plus 0.0.0.0:8000
    user: '1000'
    restart: on-failure:5
    stdin_open: false
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
      - TERM=xterm-256color
    depends_on:
      - postgres
    volumes:
      - .:/app
      - ~/.ipython:/home/django/.ipython
    ports:
      - '127.0.0.1:8000:8000'
    links:
      - postgres
      - redis
